"""Same-origin operator cockpit assets for the StageGuard API.

The browser never receives Grafana, Gemini, remediation, or infrastructure
credentials. Dynamic values are rendered with DOM text nodes, and no user data is
stored in browser persistence.
"""
from __future__ import annotations

CONSOLE_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StageGuard Operator</title><link rel="stylesheet" href="/assets/operator.css"></head><body><main>
<header><div><p class="eyebrow">LIVE MEDIA INCIDENT COMMAND</p><h1>StageGuard</h1></div><div id="connection" class="pill">Loading…</div></header>
<section class="actions"><button id="refresh">Refresh status</button><button id="investigate" class="primary">Run investigation</button><button id="briefing" disabled>Generate Gemini briefing</button></section><div id="message" role="status" aria-live="polite"></div>
<section id="integrity-safety" class="card recovery-zone" hidden aria-live="polite"><p class="eyebrow">AUDIT INTEGRITY POLICY</p><h2 id="integrity-title">Authenticated audit binding required</h2><p id="integrity-message"></p><p id="integrity-state" class="reason"></p><p class="notice">This block is independent of remediation execution state. StageGuard will not weaken a hardened deployment to make a legacy checkpoint ready.</p></section>
<section id="lifecycle-recovery" class="card recovery-zone" hidden aria-live="polite"><p class="eyebrow">FAIL-CLOSED LIFECYCLE SAFETY</p><h2 id="lifecycle-recovery-title">Lifecycle recovery required</h2><p id="lifecycle-recovery-message"></p><p id="lifecycle-recovery-reason" class="reason" hidden></p><p class="notice">Approval, execution, investigation, and briefing controls remain disabled until the server reports synchronized state. Recovery never replays a remediation action and never exposes its operation identifier.</p><div class="actions"><button id="reload-checkpoint">Reload durable checkpoint</button><button id="reconcile-execution" disabled>Reconcile uncertain execution</button></div></section>
<section id="empty" class="card"><h2>No active investigation</h2><p>Run a bounded investigation to collect the pinned Grafana evidence plane.</p></section><section id="incident" hidden>
<div class="grid"><article class="card"><p class="label">Incident</p><p id="incident-id" class="mono"></p></article><article class="card"><p class="label">Revision</p><p id="revision" class="mono"></p></article><article class="card"><p class="label">Status</p><p id="status"></p></article><article class="card"><p class="label">Confidence</p><p id="confidence"></p></article></div>
<article class="card"><h2>Deterministic diagnosis</h2><p id="summary"></p><p><strong>Hypothesis:</strong> <span id="hypothesis"></span></p><p><strong>Production:</strong> <span id="production"></span> · <strong>Feed:</strong> <span id="feed"></span></p></article><article class="card"><h2>Evidence</h2><div class="table-wrap"><table><thead><tr><th>Class</th><th>Value</th><th>Threshold</th><th>Supports</th></tr></thead><tbody id="evidence"></tbody></table></div></article><article id="briefing-card" class="card" hidden><h2>Gemini advisory briefing</h2><p class="notice">Advisory only. It cannot alter incident or remediation state.</p><pre id="briefing-output"></pre></article><article class="card"><h2>Incident timeline</h2><p class="notice">Redacted lifecycle provenance. Provider details, raw queries, targets, endpoints, activation IDs, and operator identities are excluded.</p><div class="table-wrap"><table><thead><tr><th>Seq</th><th>Time</th><th>Event</th><th>Actor ref</th><th>Details</th></tr></thead><tbody id="timeline"></tbody></table></div><div class="actions"><button id="timeline-more" disabled>Load more</button></div></article><article class="card danger-zone"><h2>Revision-bound approval</h2><p>Approval is valid only for the exact evidence revision shown above. Type the full revision to unlock approval.</p><input id="approval-revision" autocomplete="off" spellcheck="false" placeholder="Current revision"><div class="actions"><button id="approve" disabled>Approve remediation</button><button id="execute" disabled>Execute approved action</button></div><p id="approval-state" class="notice"></p></article><article id="recovery-card" class="card" hidden><h2>Recovery verification</h2><pre id="recovery"></pre></article></section></main><script src="/assets/operator.js" defer></script></body></html>"""

CONSOLE_CSS = """:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;color-scheme:dark;background:#0b0d10;color:#f4f6f8}*{box-sizing:border-box}body{margin:0;background:#0b0d10;min-height:100vh}main{max-width:1120px;margin:0 auto;padding:32px 20px 64px}header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:24px}h1{font-size:40px;margin:2px 0}h2{font-size:18px;margin:0 0 12px}.eyebrow,.label{font-size:12px;letter-spacing:.13em;text-transform:uppercase;color:#9ca7b5;margin:0}.pill{padding:8px 12px;border:1px solid #39414c;border-radius:999px;font-size:13px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0 20px}button,input{font:inherit;border-radius:8px;border:1px solid #3a4350;background:#151a21;color:#f4f6f8;padding:10px 14px}button{cursor:pointer}button.primary{background:#f2f4f7;color:#11151a;border-color:#f2f4f7;font-weight:700}button:disabled,input:disabled{opacity:.4;cursor:not-allowed}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.card{background:#11151b;border:1px solid #272e38;border-radius:12px;padding:18px;margin:12px 0}.mono,pre{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.mono{font-size:13px;overflow-wrap:anywhere}.notice{color:#aeb8c5;font-size:13px}#message{min-height:24px;color:#f3cb72}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #252c35;padding:10px 8px;vertical-align:top}th{color:#aeb8c5;font-weight:600}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0b0e12;border-radius:8px;padding:14px;font-size:13px}.danger-zone{border-color:#514327}.danger-zone input{width:min(360px,100%)}.recovery-zone{border-color:#704a2b;background:#19130f}.reason{border-left:3px solid #9d6d38;padding:10px 12px;background:#221912;border-radius:4px;font-size:14px;line-height:1.5}@media(max-width:760px){.grid{grid-template-columns:1fr 1fr}header{align-items:flex-start;flex-direction:column}}@media(max-width:460px){.grid{grid-template-columns:1fr}h1{font-size:32px}}"""

CONSOLE_JS = r"""(() => {
'use strict';const q=id=>document.getElementById(id);let current=null;let checkpointState='synchronized';let executionReconciliationState='clear';let executionReconciliationReason='clear';let auditIntegrity='disabled';let auditIntegrityPolicy='allow_unbound_legacy';let timelineAfter=0;let timelineLoading=false;
const message=text=>{q('message').textContent=text||'';};const scalar=v=>v===null||v===undefined?'—':String(v);const safeReconciliationState=v=>['clear','reload_required','reloaded'].includes(v)?v:'reload_required';const safeReconciliationReason=v=>['clear','durable_dispatching','legacy_unknown','post_dispatch_checkpoint_regression','phase_unavailable'].includes(v)?v:'phase_unavailable';const safeAuditIntegrity=v=>['disabled','unbound_legacy','verified','failed'].includes(v)?v:'failed';const safeAuditPolicy=v=>['allow_unbound_legacy','require_verified'].includes(v)?v:'require_verified';const auditPolicyBlocked=()=>auditIntegrity==='failed'||(auditIntegrityPolicy==='require_verified'&&auditIntegrity!=='verified');const lifecycleBlocked=()=>checkpointState==='conflicted'||checkpointState==='execution_uncertain'||auditPolicyBlocked();
const reconciliationGuidance=reason=>({durable_dispatching:'A durable dispatch barrier exists. The provider may already have accepted the action. Reload the durable winner, then reconcile provider state and collect fresh Grafana evidence. Do not execute remediation again.',legacy_unknown:'This checkpoint predates durable execution-phase tracking, so prior provider contact cannot be proven or excluded. Reconcile provider state and collect fresh Grafana evidence before any new approval.',post_dispatch_checkpoint_regression:'This process may have crossed the dispatch barrier, but the durable winner reports an earlier approval phase. Treat the action as potentially executed, reconcile provider state, and require fresh Grafana evidence before any new approval.',phase_unavailable:'StageGuard cannot prove a safe execution phase. Keep remediation blocked, reload durable state, and reconcile only through the idempotency status path before collecting fresh Grafana evidence.',clear:''}[reason]||'StageGuard cannot prove a safe execution phase. Keep remediation blocked until reconciliation completes.');
async function request(path,options={}){const init={method:options.method||'GET',headers:{Accept:'application/json'},credentials:'same-origin'};if(options.body!==undefined){init.headers['Content-Type']='application/json';init.body=JSON.stringify(options.body);}const response=await fetch(path,init);const data=await response.json().catch(()=>({error:'invalid_response',detail:'Server returned a non-JSON response'}));if(!response.ok)throw new Error(data.detail||data.error||`Request failed (${response.status})`);return data;}
function renderEvidence(items){const body=q('evidence');body.replaceChildren();(Array.isArray(items)?items:[]).forEach(item=>{const row=document.createElement('tr');[item.evidence_class,item.value,item.threshold,item.supports_hypothesis].forEach(v=>{const c=document.createElement('td');c.textContent=scalar(v);row.appendChild(c);});body.appendChild(row);});}
function appendTimeline(items){const body=q('timeline');(Array.isArray(items)?items:[]).forEach(item=>{const row=document.createElement('tr');const when=Number.isFinite(item.timestamp_unix_ms)?new Date(item.timestamp_unix_ms).toISOString():'—';const details=item.payload&&typeof item.payload==='object'?JSON.stringify(item.payload):'{}';[item.sequence,when,item.event_type,item.actor_ref,details].forEach(v=>{const c=document.createElement('td');c.textContent=scalar(v);row.appendChild(c);});body.appendChild(row);});}
async function loadTimeline(reset=false){if(!current||timelineLoading)return;const incidentId=current.incident_id;if(reset){timelineAfter=0;q('timeline').replaceChildren();}timelineLoading=true;q('timeline-more').disabled=true;try{const data=await request(`/v1/audit?incident_id=${encodeURIComponent(incidentId)}&after_sequence=${timelineAfter}&limit=25`);if(!current||current.incident_id!==incidentId)return;const t=data.timeline||{};appendTimeline(t.events);timelineAfter=Number.isInteger(t.next_after_sequence)?t.next_after_sequence:timelineAfter;q('timeline-more').disabled=!t.has_more;}catch(err){message(err.message);}finally{timelineLoading=false;}}
function renderIntegritySafety(){const blocked=auditPolicyBlocked();q('integrity-safety').hidden=!blocked;if(!blocked)return;const hardened=auditIntegrityPolicy==='require_verified';q('integrity-title').textContent=auditIntegrity==='failed'?'Audit integrity verification failed':'Authenticated audit binding required';q('integrity-state').textContent=`Integrity: ${auditIntegrity} · Policy: ${auditIntegrityPolicy}`;q('integrity-message').textContent=auditIntegrity==='failed'?'The durable audit lineage could not be authenticated. Lifecycle mutations remain disabled until the integrity failure is repaired and a valid checkpoint is restored.':hardened&&auditIntegrity==='unbound_legacy'?'This deployment requires a verified schema-v3 audit/checkpoint binding, but the restored checkpoint is legacy/unbound. A legitimate lifecycle write must establish authenticated v3 state; do not bypass the policy or edit checkpoint files manually.':hardened?'This hardened deployment requires verified durable audit integrity before becoming ready.':'Audit integrity is not safe for lifecycle mutation.';}
function renderLifecycleSafety(){const blocked=checkpointState==='conflicted'||checkpointState==='execution_uncertain';q('lifecycle-recovery').hidden=!blocked;q('investigate').disabled=lifecycleBlocked();q('briefing').disabled=lifecycleBlocked()||!current;q('approval-revision').disabled=lifecycleBlocked()||!current;const reason=q('lifecycle-recovery-reason');reason.hidden=true;reason.textContent='';if(checkpointState==='conflicted'){q('reload-checkpoint').disabled=false;q('reconcile-execution').disabled=true;q('lifecycle-recovery-title').textContent='Checkpoint conflict: durable reload required';q('lifecycle-recovery-message').textContent='This process lost checkpoint ownership. Reload and fully revalidate the durable winner before any incident lifecycle work can continue.';return;}if(checkpointState==='execution_uncertain'){const reloadRequired=executionReconciliationState==='reload_required';const readyToReconcile=executionReconciliationState==='reloaded';q('reload-checkpoint').disabled=!reloadRequired;q('reconcile-execution').disabled=!readyToReconcile;q('lifecycle-recovery-title').textContent=reloadRequired?'Remediation execution is uncertain: durable reload required':readyToReconcile?'Remediation execution is uncertain: ready to reconcile':'Remediation execution is uncertain: recovery state unavailable';q('lifecycle-recovery-message').textContent=reloadRequired?'Reload the durable checkpoint winner before provider reconciliation can begin. StageGuard will not replay the action.':readyToReconcile?'The durable winner has been loaded and revalidated. Reconcile provider idempotency state and collect fresh Grafana evidence; the action will not be replayed.':'Recovery remains blocked because the server did not provide a recognized reconciliation phase.';reason.textContent=reconciliationGuidance(executionReconciliationReason);reason.hidden=false;return;}q('reload-checkpoint').disabled=true;q('reconcile-execution').disabled=true;}
function render(snapshot,state='synchronized',reconciliation='clear',reason='clear',integrity='disabled',policy='allow_unbound_legacy'){const previousId=current?.incident_id;current=snapshot||null;checkpointState=typeof state==='string'?state:'failed';executionReconciliationState=safeReconciliationState(reconciliation);executionReconciliationReason=safeReconciliationReason(reason);auditIntegrity=safeAuditIntegrity(integrity);auditIntegrityPolicy=safeAuditPolicy(policy);q('empty').hidden=!!current;q('incident').hidden=!current;q('briefing-card').hidden=true;q('briefing-output').textContent='';q('approval-revision').value='';q('approve').disabled=true;renderIntegritySafety();renderLifecycleSafety();if(!current){q('timeline').replaceChildren();q('timeline-more').disabled=true;timelineAfter=0;return;}const report=current.report||{};q('incident-id').textContent=scalar(current.incident_id);q('revision').textContent=scalar(current.revision);q('status').textContent=scalar(report.status);q('confidence').textContent=Number.isFinite(report.confidence)?`${Math.round(report.confidence*100)}%`:'—';q('summary').textContent=scalar(report.summary);q('hypothesis').textContent=scalar(report.hypothesis);q('production').textContent=scalar(report.production_id);q('feed').textContent=scalar(report.affected_feed);renderEvidence(report.evidence);const approval=current.approval;q('approval-state').textContent=lifecycleBlocked()?'Lifecycle safety block active; approval and execution are disabled.':(approval?`Approved for ${scalar(approval.action)} on ${scalar(approval.target)}.`:'Not approved.');q('execute').disabled=lifecycleBlocked()||!approval||!!current.outcome;q('recovery-card').hidden=!current.outcome;q('recovery').textContent=current.outcome?JSON.stringify(current.outcome,null,2):'';loadTimeline(previousId!==current.incident_id||timelineAfter===0);}
async function refresh(){message('Refreshing incident status…');try{const data=await request('/v1/incident');render(data.incident,data.checkpoint_state,data.execution_reconciliation_state,data.execution_reconciliation_reason,data.audit_integrity,data.audit_integrity_policy);q('connection').textContent=lifecycleBlocked()?'Safety block':'Authenticated';message('');}catch(err){q('connection').textContent='Unavailable';message(err.message);}}
q('refresh').addEventListener('click',refresh);q('timeline-more').addEventListener('click',()=>loadTimeline(false));
q('investigate').addEventListener('click',async()=>{if(lifecycleBlocked())return;message('Collecting bounded Grafana evidence…');try{const data=await request('/v1/investigate',{method:'POST',body:{}});render(data.incident,'synchronized','clear','clear',data.audit_integrity,data.audit_integrity_policy);await loadTimeline(true);message('Investigation complete.');}catch(err){message(err.message);await refresh();}});
q('briefing').addEventListener('click',async()=>{if(!current||lifecycleBlocked())return;const binding={incident_id:current.incident_id,revision:current.revision};message('Generating advisory briefing for this revision…');try{const data=await request('/v1/briefing',{method:'POST',body:binding});if(!current||data.revision!==current.revision){message('Briefing discarded because the incident revision changed.');return;}q('briefing-output').textContent=JSON.stringify(data.briefing,null,2);q('briefing-card').hidden=false;await loadTimeline(true);message('');}catch(err){message(err.message);await refresh();}});
q('approval-revision').addEventListener('input',event=>{q('approve').disabled=lifecycleBlocked()||!current||event.target.value!==current.revision||current.report?.status!=='diagnosed';});
q('approve').addEventListener('click',async()=>{if(lifecycleBlocked()||!current||q('approval-revision').value!==current.revision)return;const binding={incident_id:current.incident_id,revision:current.revision};if(!window.confirm(`Approve remediation for evidence revision ${current.revision}?`))return;message('Recording explicit approval…');try{const data=await request('/v1/approve',{method:'POST',body:binding});await refresh();await loadTimeline(true);message('Remediation approved for the current revision.');}catch(err){message(err.message);await refresh();}});
q('execute').addEventListener('click',async()=>{if(lifecycleBlocked()||!current?.approval||current.outcome)return;if(!window.confirm('Execute the already-approved remediation and verify recovery telemetry?'))return;message('Executing approved remediation and verifying recovery…');try{await request('/v1/execute',{method:'POST',body:{}});await refresh();await loadTimeline(true);message('Execution finished; recovery state updated.');}catch(err){message(err.message);await refresh();}});
q('reload-checkpoint').addEventListener('click',async()=>{if(!(checkpointState==='conflicted'||checkpointState==='execution_uncertain')||q('reload-checkpoint').disabled)return;message('Reloading and validating the durable checkpoint winner…');try{const data=await request('/v1/checkpoint/reload',{method:'POST',body:{}});render(data.incident,data.checkpoint_state,data.execution_reconciliation_state,data.execution_reconciliation_reason,data.audit_integrity,data.audit_integrity_policy);await loadTimeline(true);q('connection').textContent=lifecycleBlocked()?'Safety block':'Authenticated';message(executionReconciliationState==='reloaded'?'Durable winner loaded. Execution uncertainty is ready for reconciliation.':'Durable checkpoint winner loaded and validated.');}catch(err){message(err.message);await refresh();}});
q('reconcile-execution').addEventListener('click',async()=>{if(checkpointState!=='execution_uncertain'||executionReconciliationState!=='reloaded'||auditPolicyBlocked())return;if(!window.confirm('Reconcile the uncertain execution and collect fresh Grafana evidence? This will not replay remediation.'))return;message('Reconciling provider state and collecting fresh Grafana evidence…');try{const data=await request('/v1/execution/reconcile',{method:'POST',body:{}});render(data.incident,data.checkpoint_state,data.execution_reconciliation_state,data.execution_reconciliation_reason,data.audit_integrity,data.audit_integrity_policy);await loadTimeline(true);q('connection').textContent=lifecycleBlocked()?'Safety block':'Authenticated';message('Execution uncertainty resolved with fresh evidence. Any prior approval is no longer valid.');}catch(err){message(err.message);await refresh();}});refresh();})();
"""
