#!/usr/bin/env python3
"""StageGuard operator onboarding doctor.

Runs credential-safe local checks before a user attempts the full Grafana MCP
preflight. The doctor never prints token contents, executes PromQL/LogQL, or
changes remote/local state. It is intentionally dependency-free.
"""
from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import stat
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / "runtime"
if str(RUNTIME) not in sys.path:
    sys.path.insert(0, str(RUNTIME))

from onboarding import load_telemetry_profile  # noqa: E402


@dataclass(frozen=True)
class Check:
    name: str
    status: str
    detail: str
    required: bool = True


def _check_python() -> Check:
    version = sys.version_info
    ok = version >= (3, 11)
    return Check(
        "python",
        "ok" if ok else "failed",
        f"Python {version.major}.{version.minor}.{version.micro}",
    )


def _check_config(path: Path) -> Check:
    try:
        profile = load_telemetry_profile(path)
    except Exception as exc:
        return Check("telemetry_config", "failed", f"{type(exc).__name__}: {exc}")
    return Check(
        "telemetry_config",
        "ok",
        f"valid v1 mapping for production {profile.production_id!r}",
    )


def _check_grafana_url(value: str | None) -> Check:
    if not value:
        return Check("grafana_url", "missing", "set GRAFANA_URL to your Grafana base URL")
    parsed = urlparse(value)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return Check("grafana_url", "failed", "GRAFANA_URL must be an absolute http(s) URL")
    return Check("grafana_url", "ok", f"configured host {parsed.hostname!r}")


def _check_token_file(value: str | None) -> Check:
    if not value:
        return Check(
            "grafana_token_file",
            "missing",
            "set GRAFANA_SERVICE_ACCOUNT_TOKEN_FILE to a least-privilege token file",
        )
    path = Path(value).expanduser()
    if not path.is_file():
        return Check("grafana_token_file", "failed", f"token file does not exist: {path}")
    try:
        size = path.stat().st_size
    except OSError as exc:
        return Check("grafana_token_file", "failed", f"cannot stat token file: {type(exc).__name__}")
    if size <= 0:
        return Check("grafana_token_file", "failed", "token file is empty")
    detail = f"token file exists ({size} bytes; contents not read)"
    if os.name != "nt":
        mode = stat.S_IMODE(path.stat().st_mode)
        if mode & 0o077:
            return Check(
                "grafana_token_file",
                "warning",
                f"{detail}; permissions {oct(mode)} are broader than recommended 0o600",
            )
    return Check("grafana_token_file", "ok", detail)


def _check_mcp_command(value: str | None) -> Check:
    command = value or "mcp-grafana"
    try:
        # POSIX shlex treats Windows drive/path backslashes as escape
        # characters. Preserve native Windows launcher paths while retaining
        # normal shell splitting on POSIX.
        argv = shlex.split(command, posix=os.name != "nt")
        if os.name == "nt":
            argv = [item.strip('"') for item in argv]
    except ValueError as exc:
        return Check("grafana_mcp", "failed", f"invalid STAGEGUARD_MCP_COMMAND: {exc}")
    if not argv:
        return Check("grafana_mcp", "failed", "STAGEGUARD_MCP_COMMAND is empty")
    executable = argv[0]
    if executable in {"docker", "podman"}:
        found = shutil.which(executable)
        return Check(
            "grafana_mcp",
            "ok" if found else "missing",
            f"container launcher {'found' if found else 'not found'}: {executable}",
        )
    found = shutil.which(executable)
    if found:
        return Check("grafana_mcp", "ok", f"MCP executable found: {found}")
    return Check(
        "grafana_mcp",
        "missing",
        "install the official grafana/mcp-grafana binary or set STAGEGUARD_MCP_COMMAND",
    )


def _optional_path(name: str, value: str | None) -> Check:
    if not value:
        return Check(name, "missing", "not configured yet; generated by runtime/preflight.py", required=False)
    path = Path(value).expanduser()
    return Check(
        name,
        "ok" if path.is_file() else "missing",
        f"{'found' if path.is_file() else 'not found'}: {path}",
        required=False,
    )


def _next_steps(checks: list[Check], config: Path) -> list[str]:
    by_name = {check.name: check for check in checks}
    steps: list[str] = []
    if by_name["grafana_url"].status != "ok":
        steps.append("Set GRAFANA_URL to your Grafana Cloud or self-hosted instance.")
    if by_name["grafana_token_file"].status not in {"ok", "warning"}:
        steps.append("Create a least-privilege Grafana Viewer/service-account token file and set GRAFANA_SERVICE_ACCOUNT_TOKEN_FILE.")
    if by_name["grafana_mcp"].status != "ok":
        steps.append("Install the official Grafana MCP binary or configure STAGEGUARD_MCP_COMMAND to launch it read-only.")
    if not steps:
        steps.append(
            "Run: python runtime/preflight.py "
            f"{config} --activation-output .stageguard/activation.json "
            "--log-activation-output .stageguard/log-activation.json"
        )
    return steps


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Check local prerequisites for connecting StageGuard to an existing Grafana deployment."
    )
    parser.add_argument(
        "config",
        nargs="?",
        default=str(RUNTIME / "telemetry.example.json"),
        help="StageGuard telemetry mapping JSON (default: runtime/telemetry.example.json)",
    )
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    args = parser.parse_args(argv)

    config = Path(args.config).expanduser()
    checks = [
        _check_python(),
        _check_config(config),
        _check_grafana_url(os.getenv("GRAFANA_URL")),
        _check_token_file(os.getenv("GRAFANA_SERVICE_ACCOUNT_TOKEN_FILE")),
        _check_mcp_command(os.getenv("STAGEGUARD_MCP_COMMAND")),
        _optional_path("metric_activation", os.getenv("STAGEGUARD_METRIC_ACTIVATION")),
        _optional_path("log_activation", os.getenv("STAGEGUARD_LOG_ACTIVATION")),
    ]
    hard_failures = [
        check for check in checks if check.required and check.status in {"failed", "missing"}
    ]
    payload = {
        "ready_for_preflight": not hard_failures,
        "checks": [asdict(check) for check in checks],
        "next_steps": _next_steps(checks, config),
    }

    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("StageGuard onboarding doctor")
        print("===========================")
        for check in checks:
            marker = {"ok": "PASS", "warning": "WARN", "missing": "MISS", "failed": "FAIL"}[check.status]
            requirement = "required" if check.required else "optional"
            print(f"[{marker}] {check.name} ({requirement}): {check.detail}")
        print("\nNext steps:")
        for index, step in enumerate(payload["next_steps"], 1):
            print(f"  {index}. {step}")

    return 0 if not hard_failures else 2


if __name__ == "__main__":
    raise SystemExit(main())
